server:
  port: 8090

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: microservice-1
          uri: lb://microservice-1
          predicates:
            - Path=/microservice-1/**
        - id: microservice-2
          uri: lb://microservice-2
          predicates:
            - Path=/microservice-2/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
