server:
  port: 8090

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-server
          uri: lb://auth-server
          predicates:
            - Path=/auth-server/**
          filters:
            - RewritePath=/auth-server/(?<remaining>.*), /${remaining}
        - id: microservice-1
          uri: lb://microservice-1
          predicates:
            - Path=/microservice-1/**
          filters:
            - RewritePath=/microservice-1/(?<remaining>.*), /${remaining}
        - id: microservice-2
          uri: lb://microservice-2
          predicates:
            - Path=/microservice-2/**
          filters:
            - RewritePath=/microservice-2/(?<remaining>.*), /${remaining}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
