server:
  port: 8090

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
  cloud:
    gateway:
      routes:
        - id: microservice-1
          uri: http://localhost:8080
          predicates:
            - Path=/microservice-1/**
