server:
  port: 8082

spring:
  application:
    name: mail-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  cloud:
    function:
      definition: "newAccount;placeOrder"
    stream:
      default-binder: rabbit
      bindings:
        newAccount-in-0:
          destination: sendEmail
          group: newAccount
          content-type: application/json
          binder: rabbit
        placeOrder-in-0:
          destination: sendEmail
          group: placeOrder
          content-type: application/json
          binder: rabbit
      rabbit:
        bindings:
          newAccount-in-0:
            consumer:
              republish-to-dlq: false
              binding-routing-key: new-account
          placeOrder-in-0:
            consumer:
              republish-to-dlq: false
              binding-routing-key: place-order

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true