server:
  port: 8081

spring:
  application:
    name: microservice-2
  r2dbc:
    url: r2dbc:h2:file:///./testdb;AUTO_SERVER=TRUE
    password:
  h2:
    console:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
      client:
        provider:
          client-microservice-1:
            token-uri: http://localhost:9000/oauth2/token
        registration:
          client-microservice-1:
            authorization-grant-type: client_credentials
            client-id: client-microservice-1
            client-secret: client-microservice-1
  cloud:
    stream:
      default-binder: rabbit
      bindings:
        sendEmail:
          destination: sendEmail
      rabbit:
        bindings:
          sendEmail:
            producer:
              routing-key-expression: headers['routingKey']

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    webclient:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

microservice-1:
  url: http://microservice-1