server:
  port: 8081

spring:
  application:
    name: microservice-2
  datasource:
    url: jdbc:h2:file:./testdb;NON_KEYWORDS=order;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
  cloud:
    stream:
      default-binder: rabbit
      bindings:
        sendEmail:
          destination: sendEmail
      rabbit:
        bindings:
          sendEmail:
            producer:
              routing-key-expression: headers['routingKey']

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

logging:
  pattern:
    level: "%5p"
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%15.15t] %-40.40logger{39} : %msg%n%ex"